### ISSUE TITLE
`paramListToForm` fails to build with `http-api-data` >= 0.7

### ISSUE THREAD

**Issue by Stanley** [scotty-web/scotty#428]
## Description

  Scotty 0.30 fails to build when the solver picks `http-api-data >= 0.7`, which changed the `Form` representation from `HashMap Text [Text]` to `Map Text [Text]` (for HashDoS mitigation).

  ## Error

  Web/Scotty/Action.hs:459:97: error:
      • Couldn't match expected type: Map.Map T.Text [T.Text]
                    with actual type: HM.HashMap k0 v0
      • In the second argument of 'foldl'', namely 'HM.empty'
        In the second argument of '(.)', namely
          'foldl' (\ f (k, v) -> HM.alter (prependValue v) k f) HM.empty'

  ## Cause

  `paramListToForm` uses `HM.empty` and `HM.alter` but the `Form` constructor now wraps `Map.Map
  T.Text [T.Text]`:

  ```haskell
  paramListToForm = Form . fmap reverse . foldl' (\f (k, v) -> HM.alter (prependValue v) k f) HM.empty
  ```

  ## Fix

  Replace the `HashMap` operations with `Map` equivalents:

  ```haskell
  paramListToForm = Form . fmap reverse . foldl' (\f (k, v) -> Map.alter (prependValue v) k f) Map.empty
  ```

  And update the imports accordingly (`Data.Map.Strict` instead of / in addition to `Data.HashMap.Strict`).

**Comment by ocramz** [comment]
Thank you @Stanley , indeed it's an easy fix but last time I tried it before cutting release 0.30 I ran into build failures related to other dependencies, so opted to keep http-api-data < 0.7 for now.
It's just a matter of time other dependencies update and we can remove this band-aid.

**Comment by ysangkok** [comment]
which are the dependencies that need to update? Because there aren't a lot remaining in

* https://github.com/commercialhaskell/stackage/issues/7912

**Comment by ysangkok** [comment]
@ocramz all the dependencies seem to build fine for me. which dependencies do you have issues with? i tested with ghc-9.12.4

**Comment by ocramz** [comment]
@ysangkok @Stanley happy to merge a patch that keeps CI green for (most of) our supported GHC versions .
