### PR TITLE
Bump lower bounds, allow GHC 9.14

### LINKED ISSUE #428: `paramListToForm` fails to build with `http-api-data` >= 0.7
## Description

  Scotty 0.30 fails to build when the solver picks `http-api-data >= 0.7`, which changed the `Form` representation from `HashMap Text [Text]` to `Map Text [Text]` (for HashDoS mitigation).

  ## Error

  Web/Scotty/Action.hs:459:97: error:
      • Couldn't match expected type: Map.Map T.Text [T.Text]
                    with actual type: HM.HashMap k0 v0
      • In the second argument of 'foldl'', namely 'HM.empty'
        In the second argument of '(.)', namely
          'foldl' (\ f (k, v) -> HM.alter (prependValue v) k f) HM.empty'

  ## Cause

  `paramListToForm` uses `HM.empty` and `HM.alter` but the `Form` constructor now wraps `Map.Map
  T.Text [T.Text]`:

  ```haskell
  paramListToForm = Form . fmap reverse . foldl' (\f (k, v) -> HM.alter (prependValue v) k f) HM.empty
  ```

  ## Fix

  Replace the `HashMap` operations with `Map` equivalents:

  ```haskell
  paramListToForm = Form . fmap reverse . foldl' (\f (k, v) -> Map.alter (prependValue v) k f) Map.empty
  ```

  And update the imports accordingly (`Data.Map.Strict` instead of / in addition to `Data.HashMap.Strict`).

### LINKED ISSUE #430: Compile error on GHC-9.14.1
I get an error attempting a compile on ghc-9.14.1:

```
[ 4 of 11] Compiling Web.Scotty.Action ( Web/Scotty/Action.hs, dist/build/Web/Scotty/Action.o, dist/build/Web/Scotty/Action.dyn_o )
Web/Scotty/Action.hs:459:66: error: [GHC-83865]
    • Couldn't match expected type: Map.Map T.Text [T.Text]
                  with actual type: HM.HashMap T.Text [T.Text]
    • In the expression: HM.alter (prependValue v) k f
      In the first argument of ‘foldl'’, namely
        ‘(\ f (k, v) -> HM.alter (prependValue v) k f)’
      In the second argument of ‘(.)’, namely
        ‘foldl' (\ f (k, v) -> HM.alter (prependValue v) k f) HM.empty’
    |
459 |     paramListToForm = Form . fmap reverse . foldl' (\f (k, v) -> HM.alter (prependValue v) k f) HM.empty
    |                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Scotty/Action.hs:459:94: error: [GHC-83865]
    • Couldn't match expected type: HM.HashMap T.Text [T.Text]
                  with actual type: Map.Map T.Text [T.Text]
    • In the third argument of ‘HM.alter’, namely ‘f’
      In the expression: HM.alter (prependValue v) k f
      In the first argument of ‘foldl'’, namely
        ‘(\ f (k, v) -> HM.alter (prependValue v) k f)’
    |
459 |     paramListToForm = Form . fmap reverse . foldl' (\f (k, v) -> HM.alter (prependValue v) k f) HM.empty
    |                                                                                              ^

Web/Scotty/Action.hs:459:97: error: [GHC-83865]
    • Couldn't match expected type: Map.Map T.Text [T.Text]
                  with actual type: HM.HashMap k0 v0
    • In the second argument of ‘foldl'’, namely ‘HM.empty’
      In the second argument of ‘(.)’, namely
        ‘foldl' (\ f (k, v) -> HM.alter (prependValue v) k f) HM.empty’
      In the second argument of ‘(.)’, namely
        ‘fmap reverse
           . foldl' (\ f (k, v) -> HM.alter (prependValue v) k f) HM.empty’
    |
459 |     paramListToForm = Form . fmap reverse . foldl' (\f (k, v) -> HM.alter (prependValue v) k f) HM.empty
    |                                                                                                 ^^^^^^^^

Error: [Cabal-7125]
Failed to build scotty-0.30 (which is required by exe:web-rep-example from web-rep-0.14.1.0). See the build log above for details.
```

### PR DESCRIPTION
**Pull request by ysangkok**
Fixes #428 , fixes #430

### CODE REVIEW

**Comment by ocramz** [comment]
thank you @ysangkok !

File: changelog.md [hunk 1]
```diff
@@ -1,3 +1,8 @@
+## Next
+
+* Added support for GHC 9.14, containers-0.8 (a boot lib).
+* Raise lower bounds for a lot of dependencies
```
Comment (ocramz) [inline changelog.md:6]: Could you please mark this as a Breaking change?

Comment (ysangkok) [reply changelog.md:6]: Fixed in 979c73098070a7d001050eec652b7c91cdd757cc
