### ISSUE TITLE
Compile error on GHC-9.14.1

### ISSUE THREAD

**Issue by tonyday567** [scotty-web/scotty#430]
I get an error attempting a compile on ghc-9.14.1:

```
[ 4 of 11] Compiling Web.Scotty.Action ( Web/Scotty/Action.hs, dist/build/Web/Scotty/Action.o, dist/build/Web/Scotty/Action.dyn_o )
Web/Scotty/Action.hs:459:66: error: [GHC-83865]
    • Couldn't match expected type: Map.Map T.Text [T.Text]
                  with actual type: HM.HashMap T.Text [T.Text]
    • In the expression: HM.alter (prependValue v) k f
      In the first argument of ‘foldl'’, namely
        ‘(\ f (k, v) -> HM.alter (prependValue v) k f)’
      In the second argument of ‘(.)’, namely
        ‘foldl' (\ f (k, v) -> HM.alter (prependValue v) k f) HM.empty’
    |
459 |     paramListToForm = Form . fmap reverse . foldl' (\f (k, v) -> HM.alter (prependValue v) k f) HM.empty
    |                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Scotty/Action.hs:459:94: error: [GHC-83865]
    • Couldn't match expected type: HM.HashMap T.Text [T.Text]
                  with actual type: Map.Map T.Text [T.Text]
    • In the third argument of ‘HM.alter’, namely ‘f’
      In the expression: HM.alter (prependValue v) k f
      In the first argument of ‘foldl'’, namely
        ‘(\ f (k, v) -> HM.alter (prependValue v) k f)’
    |
459 |     paramListToForm = Form . fmap reverse . foldl' (\f (k, v) -> HM.alter (prependValue v) k f) HM.empty
    |                                                                                              ^

Web/Scotty/Action.hs:459:97: error: [GHC-83865]
    • Couldn't match expected type: Map.Map T.Text [T.Text]
                  with actual type: HM.HashMap k0 v0
    • In the second argument of ‘foldl'’, namely ‘HM.empty’
      In the second argument of ‘(.)’, namely
        ‘foldl' (\ f (k, v) -> HM.alter (prependValue v) k f) HM.empty’
      In the second argument of ‘(.)’, namely
        ‘fmap reverse
           . foldl' (\ f (k, v) -> HM.alter (prependValue v) k f) HM.empty’
    |
459 |     paramListToForm = Form . fmap reverse . foldl' (\f (k, v) -> HM.alter (prependValue v) k f) HM.empty
    |                                                                                                 ^^^^^^^^

Error: [Cabal-7125]
Failed to build scotty-0.30 (which is required by exe:web-rep-example from web-rep-0.14.1.0). See the build log above for details.
```

**Comment by ocramz** [comment]
Hi @tonyday567 ! Yes this is related to #428
